export const DI_ROOT_INJECTOR_KEY = '__DI__ROOT__INJECTOR__';
export const DI_GLOBAL_STATE_STORE = '__DI__GLOBAL_STATE_STORE';
export const GLOBAL_INSTANCE_MAP = 'GLOBAL_INSTANCE_MAP';
export const GLOBAL_REGISTRATION_MAP = 'GLOBAL_REGISTRATION_MAP';
export const GLOBAL_CONFIGURATION = 'GLOBAL_CONFIGURATION';
export const INJECTOR_TYPE_ID = '5495541b-7416-42a6-a830-065fe591591a';
